embeddings {
    tensor_name: 'embeddings/decoder/embedding_decoder'
    metadata_path: 'decoder.tsv'
}
embeddings {
    tensor_name: 'embeddings/encoder/embedding_encoder'
    metadata_path: 'encoder.tsv'
}